version: '3.7'
services:
  
  kanban:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_CONFIG=production
      - FLASK_ENV=PROD
      - MIGRATE_DB=1
    volumes:
      - ./kanban:/kanban
      - ./data:/data:rw

